### ISSUE TITLE
All sentinel-2 items acquired after 5 July 2018 are missing from the sat-api catalog

### ISSUE THREAD

**Issue by carlodef** [sat-utils/sat-api#79] opened 2018-08-17 15:37 UTC
It seems that all sentinel-2 items acquired after 5 July 2018 are missing from the sat-api catalog at https://sat-api/developmentseed.org/search/stac.

This API request:

https://sat-api.developmentseed.org/search/stac?limit=1000&c:id=%22sentinel-2%22&datetime=2018-07-05/2019-01-01

returns no results:

> {"type":"FeatureCollection","properties":{"found":0,"limit":1000,"page":1},"features":[]}

while there are many sentinel-2 images acquired after 2018-07-05 that are available on AWS. For instance this one: https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/30/N/TJ/2018/8/16/0/

Is that expected?

**Comment by matthewhanson** [comment] 2018-08-18 10:53
@carlodef The problem is that the switch of Sentinel-2 to a requestor pays bucket broke the ingestion of data into sat-api because the metadata was getting ingested from the bucket as well and unfortunately all files (including metadata) are now requestor pays.

We need to update the sat-api ingestion process, hoping this will be fixed in the coming weeks.

**Comment by carlodef** [comment] 2018-08-18 17:40
@matthewhanson Ok, thanks for the clarifications. However, according to [this post](https://forum.sentinel-hub.com/t/changes-of-the-access-rights-to-l1c-bucket-at-aws-public-datasets-requester-pays/172) the metadata is still and will stay freely accessible at [this url](https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/), isn't it?

**Comment by matthewhanson** [comment] 2018-08-19 19:51
@carlodef yes it is accessible through that URL, but the current ingestion is still trying to read from the bucket, so I've got to update the code to use the new endpoint.

**Comment by carlodef** [comment] 2018-08-30 10:13
@matthewhanson Thanks! Is there something I can contribute to help with this update?

**Comment by matthewhanson** [comment] 2018-08-30 14:37
Sorry for the delay @carlodef I'm at FOSS4G conf, but should be able to get this fixed after my talks tomorrow.

**Comment by carlodef** [comment] 2018-09-05 06:50
Thank you @matthewhanson, let me know if I can help!

**Comment by shiweihappy** [comment] 2018-09-12 05:40
now it is ok

https://sat-api.developmentseed.org/search/stac?datetime=2018-09-06&limit=1&page=1&c:id=sentinel-2

response: 

```
type: "FeatureCollection",
properties: {
    found: 2944,
    limit: 1,
    page: 1
},
...
```

**Comment by carlodef** [comment] 2018-09-12 06:41
A lot of products are still missing. For example:

https://sat-api.developmentseed.org/search/stac?limit=1000&c:id=%22sentinel-2%22&sentinel:product_id=%22S2B_MSIL1C_20180803T094029_N0206_R036_T33QTE_20180803T132643%22

gives

> {"type":"FeatureCollection","properties":{"found":0,"limit":1000,"page":1},"features":[]}

while this product is available here:

https://roda.sentinel-hub.com/sentinel-s2-l1c/tiles/33/Q/TE/2018/8/3/0/productInfo.json

**Comment by matthewhanson** [comment] 2018-09-13 02:10
@carlodef It is ingesting new records, but I'm currently backfilling it with the missing data, it should be complete in the next day.

**Closed** 2018-11-27 18:50 UTC
